version: '3.7'

services:
  mysql-master:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - type: bind
        source: ./mysql-master.cnf
        target: /etc/mysql/conf.d/mysql-master.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_pw
      - MYSQL_DATABASE=my_database
    command: ["--log-bin=my"]
