USE mysql;
CREATE DATABASE docker;
-- CREATE USER 'root'@'%' IDENTIFIED BY 'PASSWORD';
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
-- CREATE USER 'docker'@'%' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON *.*  TO 'my_user'@'*';
-- GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
-- GRANT ALL PRIVILEGES ON *.* TO 'docker'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;
